Finish route aggregator implementation
AdaCore/OpenUxAS-SoI pull request #44
Opened 2020-05-28 18:16 UTC by joffreyhuguet

2020-05-28 18:49 UTC, pat-rogers submitted a review, later dismissed
LGTM

2020-05-28 21:14 UTC, manthonyaiello requested changes
The build succeeds, but the example does not run correctly for me. Both OpenUxAS's start up and I see the Ada OpenUxAS report that it's started the two services. OpenAMASE starts; when I click run, however, the assignment never takes place. I tried a few times and compared with the original Ada waterway example — which still works.

2020-05-29 14:56 UTC, pat-rogers approved these changes
Per Slack discussion

2020-06-01 12:46 UTC, manthonyaiello approved these changes

2020-06-01 12:47 UTC, merged